CREATE TABLE ROLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE USER_WALLET (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CURRENCY DECIMAL(18,2) NOT NULL
);

CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CPF BIGINT NOT NULL UNIQUE,
    CNPJ BIGINT,
    NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FID_USER_WALLET INT,
    FOREIGN KEY (FID_USER_WALLET) REFERENCES USER_WALLET(ID)
);

CREATE TABLE USER_ROLE (
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

CREATE TABLE TRANSACTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(18,2) NOT NULL,
    FID_USER_PAYER INT NOT NULL,
    FID_USER_PAYEE INT NOT NULL,
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(30) NOT NULL,
    FOREIGN KEY (FID_USER_PAYER) REFERENCES USERS(ID),
    FOREIGN KEY (FID_USER_PAYEE) REFERENCES USERS(ID)
);