CREATE TABLE ROLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE WALLET (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CURRENCY DECIMAL(18,2) NOT NULL
);

CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT VARCHAR(20) NOT NULL UNIQUE,
    NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    WALLET_ID INT,
    ROLE_ID INT,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
    FOREIGN KEY (WALLET_ID) REFERENCES WALLET(ID)
);

CREATE TABLE TRANSACTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DECIMAL(18,2) NOT NULL,
    FID_USER_PAYER INT NOT NULL,
    FID_USER_PAYEE INT NOT NULL,
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(30) NOT NULL,
    FOREIGN KEY (FID_USER_PAYER) REFERENCES USERS(ID),
    FOREIGN KEY (FID_USER_PAYEE) REFERENCES USERS(ID)
);

INSERT INTO ROLE (ROLE) VALUES ('LOJISTA');
INSERT INTO ROLE (ROLE) VALUES ('CLIENTE');
